server:
  port: 8083
  
spring:
  data:
    mongodb:
      port: 27017
      database: seriesBackendFinal

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
message: Hello from Serie Server

management:
  endpoints:
    web:
      exposure:
        include: '*'
