server:
  port: 8083
  
spring:
  data:
    mongodb:
      port: 27017
      database: seriesBackendFinal
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    
queue:
  movie:
    name: serieQueue
zipkin:
  base-url: http://localhost:9411/

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
message: Hello from Serie Server

management:
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
